AllCops:
  TargetRubyVersion: 3.2
  NewCops: enable
  SuggestExtensions: false

Gemspec/DevelopmentDependencies:
  Enabled: false

Gemspec/RequireMFA:
  Enabled: false

Lint/DuplicateBranch:
  Enabled: false

Metrics/AbcSize:
  Max: 35

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*_spec.rb'
    - '*.gemspec'

Metrics/CyclomaticComplexity:
  Max: 15

Metrics/MethodLength:
  Max: 30

Metrics/ModuleLength:
  Max: 250

Metrics/PerceivedComplexity:
  Max: 12

Layout/LineLength:
  Max: 200

Style/Documentation:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes
