AllCops:
  TargetRubyVersion: 3.2
  NewCops: enable
  SuggestExtensions: false

Gemspec/DevelopmentDependencies:
  Enabled: false

Gemspec/RequireMFA:
  Enabled: false

Lint/DuplicateBranch:
  Enabled: false

Metrics/AbcSize:
  Max: 35

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*_spec.rb'
    - '*.gemspec'

Metrics/CyclomaticComplexity:
  Max: 15

Metrics/MethodLength:
  Max: 30

Metrics/ModuleLength:
  Max: 250

Metrics/PerceivedComplexity:
  Max: 12
  Exclude:
    - 'lib/interactor/validation/validates.rb' # validate_param method is intentionally complex
    - 'lib/interactor/validation/validators/hash.rb' # validate_nested_attribute method is intentionally complex

Lint/NonLocalExitFromIterator:
  Exclude:
    - 'lib/interactor/validation/validates.rb' # Early return in iterator for halt behavior

Layout/LineLength:
  Max: 200

Style/Documentation:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes
